### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by AeliusSaionji**
Just proposing a few simplifications before I tackle the removal of geforce experience and the updater.

### CODE REVIEW

**Comment by aronovgj** [comment]
Did you test it?

**Comment by AeliusSaionji** [comment]
I did not test the package as a whole yet, give me 5 minutes

**Comment by aronovgj** [comment]
No rush. If you tell me it works I'll merge.

**Comment by AeliusSaionji** [comment]
Somehow `Nvidia Update` is being listed as installed in the control panel even though it is not installed. Other than that though, everything works as desired.

**Comment by aronovgj** [comment]
Maybe it is some value that gets written to the registry by the installer?

**Comment by AeliusSaionji** [comment]
Probably. It's not hurting anything, though, and it "uninstalls" fine (even though there is nothing to uninstall).

**Comment by aronovgj** [comment]
I'd rather not have it in the control panel. But ok, let's merge.

**Comment by AeliusSaionji** [comment]
I'll keep looking- this didn't happen when I tried the other week.

How do you feel about moving the `nvidiadriver.zip` outside of the nvidiadriver folder? At the end of the script, you delete the nvidiadriver folder, which means the installer is not cached and must be redownloaded.

**Comment by aronovgj** [comment]
Good point. Go ahead :)

**Pull request merged**
