### PR TITLE
geforce-game-ready-driver package upgrade

### PR DESCRIPTION
**Pull request by Tithen-Firion**
I edited this package so now it supports notebook and Windows 10 drivers.

### CODE REVIEW

**Comment by aronovgj** [comment]
Thanks, I'll check it out the next days.

**Comment by aronovgj** [comment]
- So, Nvidia is sometimes pushing different versions for different cards. Or it might skip a version for a certain card. What if this happens?
  Packages would then on each update be downloaded but it would not install? Or would it just reinstall the same package? Both cases are actually bad...
- What will happen to the package versions if version fragmentation happens? New packages would be pushed with a lower version number. They would then not show up at the first place on chocolatey.org and therefore they would not be installed by just `cinst geforce-game-ready-driver` but the package with the highest version would be installed.
  We don't want that either.
- Would this also push packages with betas? The links you check are pretty confusing, don't know how you found them :D. Betas should not be pushed as stable packages but they should be marked as previews in the `.nuspec`. For this I have another Ketarin instance with extra packages (which is not on github)
- Although people do misuse checksum variables for passing links, I really don't like this "hack". What if a usable way to generate checksums for packages will be finally released? I'd like to actually use checksums some day.

I'm beginning to think that different packages are a better idea. The scripts would be smaller and it would reduce possible issues.

**Comment by aronovgj** [comment]
Forget point three, have read your comment.

Regarding point 1 and 2:

GTX 465:
http://www.nvidia.com/Download/processFind.aspx?psid=95&pfid=694&osid=41&lid=1&whql=&lang=en-us

GTX 420:
http://www.nvidia.com/Download/processFind.aspx?psid=71&pfid=538&osid=41&lid=1&whql=&lang=en-us

The current version is the same but in the past you see that they were different

**Comment by aronovgj** [comment]
https://gitter.im/chocolatey/choco?at=55dbb1e736e894436a9ae50b
asked people think about different packages

**Comment by Tithen-Firion** [comment]
1 & 2: This problem exists in your package right now too. You check driver version only for `GeForce GT 610` card. But yeah, you're right -- with 4 different drivers (8 if you count 32/64 bitness) this would be more common.
3: I got those links from [geforce.com](http://www.geforce.com/drivers). I have no idea where did you get yours. Form on [nvidia.com](http://www.nvidia.com/Download/index.aspx?lang=en-us) redirects me directly to driver description, not driver list. By the way, your Ketarin profile doesn't find newest driver version. Example: [GeForce 405](http://www.nvidia.com/Download/processFind.aspx?psid=71&pfid=572&osid=41&lid=1&whql=1&lang=en-us) (note the `whql=1` for no betas).
4: I know it's "hackish" and I don't like it, but it was the only way to do it with `chocopkgup` right now.

Again 1 & 2: 
If version fragmentation can happen to any card, then we should have separate packages for each, which is pointless.

It is possible to write PowerShell script that would get graphics card name and search for driver url itself, but I would have to know exact values returned by PowerShell's `(gwmi win32_VideoController).Name` for cards like: `GeForce GTX 760 Ti (OEM)`, `GeForce GTX 650 Ti BOOST`, `GeForce GTX 560 SE`, `GeForce GTX 460 SE v2`, `GeForce GT 640M LE`.

**Comment by aronovgj** [comment]
> 3: I got those links from geforce.com. I have no idea where did you get yours. Form on nvidia.com redirects me directly to driver description, not driver 

Lots of googling. I spent quite a lot of time to find a page where I could get drivers versions and finally found that.

> By the way, your Ketarin profile doesn't find newest driver version. Example: GeForce 405 (note the whql=1 for no betas).

Yes, that is part of the fragmentation issue. Do you know if the newer versions would be compatible since some versions overlap?

@ferventcoder said that multiple packages would be ok. I'm also not sure whether this is a good idea...

**Comment by aronovgj** [comment]
Lets see how this will work out:
https://github.com/Tithen-Firion/chocolatey-packages/tree/master/geforce-driver

Thanks @Tithen-Firion anyway

**Pull request closed without merging**
