### PR TITLE
nvidia driver Win10 Support

### PR DESCRIPTION
**Pull request by AeliusSaionji**
There are different packages for Desktop and Notebook, but they _appear_ to be the same thing. I'll look further into that.

### CODE REVIEW

**Comment by AeliusSaionji** [comment]
Yep, the notebook and desktop installers have the exact same checksum.

**Comment by aronovgj** [comment]
Thanks,

if you haven't, check out this discussion:
https://github.com/aronovgj/choco-auto/pull/2

The issues that I state in the pull request above are the same as for this pull request. 

Any way to ensure that between Win 10 and Win 7-8.1  no fragmentation happens? Nvidia probably released different installers for a reason. I don't want situations where for example the Win 7 links work and the Win 10 links don't because there were fixes for only one of the OS versions. This would make troubleshooting even harder since I only have Win 7 at the moment to test on.

**Comment by AeliusSaionji** [comment]
afaik nvidia releases every single installer for every card, for every change they make. There are no specific releases, so this should never be an issue.

**Comment by AeliusSaionji** [comment]
An update where the changelog is specifically for "x card on windows y" still gets released for everyone as an update.

**Comment by AeliusSaionji** [comment]
If you're not convinced that this is the case, I suggest you make a new package `geforce-game-ready-driver-legacy` and maintain exclusive pre-10 support there. Accept my PR, but add this to the `Else` line

``` powershell
Write-Warning "If the download fails, try geforce-game-ready-driver-legacy"
```

**Comment by aronovgj** [comment]
> afaik nvidia releases every single installer for every card, for every change they make. There are no specific releases, so this should never be an issue.

As I showed here https://github.com/aronovgj/choco-auto/pull/2#issuecomment-134419049 this is not the case. There are a lot of different installers for a lot of different cards with sometimes different versions. Thats why @Tithen-Firion created his package in the first place, which attempts to cover all Windows versions for all Nvidia cards. The problem already starts in the way I check for new versions with Ketarin (using the links in the post).

> If you're not convinced that this is the case, I suggest you make a new package geforce-game-ready-driver-legacy and maintain exclusive pre-10 support there. Accept my PR, but add this to the Else line

I don't want this package to drop support for cards it is supporting right now if it is not absolutely necessary. Also, having three packages for Nvidia cards, we should think abouth whether so many of them are really necessary. 

As I already told @Tithen-Firion, if you think you can improve the package without losing any currently offered functionality, I can add you as a maintainer.

**Comment by AeliusSaionji** [comment]
Your link demonstrates that they organize the same release under different names. Follow the links, get the same download page. Find me a download where the checksums don't match, and I'll be convinced. I used an ancient nvidia card for 4 years and every other week I downloaded the same exact generic update everyone else downloaded. Windows 10 having a separate installer is the first deviation from one-installer I've seen from nvidia since 2008/nview/nforce days.

**Comment by aronovgj** [comment]
https://www.nvidia.com/Download/processFind.aspx?psid=95&pfid=694&osid=41&lid=1&whql=&lang=en-us
has the version 353.06

https://www.nvidia.com/Download/processFind.aspx?psid=71&pfid=538&osid=41&lid=1&whql=&lang=en-us
doesn't show such a version. Does it hide under a different version? Which of those versions has the same installer as you are offered in 353.06?

Even if two different versions have the same content, how do you propose to deal with the versioning in such a case?

**Comment by AeliusSaionji** [comment]
You're right, the supported products list for 353.06 is not the same as the 353.30.

However, this is irrelevant to my PR, and it was irrelevant to @Tithen-Firion 's PR too- accepting either PR will not fix or break the fact that your package, as is, is susceptible to the same thing. Windows 10 support is the focus of this PR.

Now, as for versioning, I'm not sure what you think needs to be changed. It grabs the latest generic installer. I believe it will install on all cards*, but in the event that it fails for an individual, they just have to try again next release. Your links show that divergences are eventually re-merged.

*I'm reasonably certain that the installer will install on all cards, even the unlisted ones- I believe legacy drivers are packaged in every release.

**Comment by aronovgj** [comment]
Fine, lets try it.

**Pull request merged**
