### PR TITLE
Add custom urls for MikTeX mirrors

### PR DESCRIPTION
**Pull request by eyenir**
Added an optional parameter `--a` to which a user may supply his custom links for downloading MiKTeX.

### CODE REVIEW

**Comment by aronovgj** [comment]
- What would be the syntax to install the package using the custom URLs? 
  This does not seem to work:
  `choco install miktex --a "http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex.exe, http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe"`
- Could it also happen that the way you implemented it, the parameter could prevent other parameters from working? Would for example `choco install miktex -f -d --a="someurls"` work?

**Comment by aronovgj** [comment]
And a comment in the `.nuspec` description would be nice with a short example of how to use the parameter.

**Comment by eyenir** [comment]
I don't think I can check if it works. My original intention was to pass 3 vars in the so called "usual way for install args", which means `choco install miktex --ia [--a,http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex.exe,http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-x64.exe]`. Let me know if that works for you. If so, I'll update the `.nuspec` file. Sorry for the mess.

**Comment by eyenir** [comment]
About the second question: No, because the urls are supplied as part of `--ia`. The last `else` checks indeed that the user doesn't confuse choco's flags with the installation arguments.

**Comment by aronovgj** [comment]
That does not seem to work.

https://chocolatey.org/docs/commands-install
`--ia, --installargs, --installarguments, --install-arguments=VALUE
     InstallArguments - Install Arguments to pass to the native installer in 
       the package. Defaults to unspecified.`

For the script that means that it will modify `$silentArgs`. It will not change the URLs.

**Comment by aronovgj** [comment]
Also, no matter how the install command looks like, I never am able to make the script change to the `elseif` part. Sure `$PSBoundParameters.Keys.Count` is the right thing to check for?

**Comment by aronovgj** [comment]
https://chocolatey.org/packages/jdk8

might be helpful in figuring out how to deal with parameters

Easier:
https://chocolatey.org/packages/treesizefree

**Comment by aronovgj** [comment]
This seems to go nowhere so I'm closing it...

**Pull request closed without merging**
